### ISSUE TITLE
CR: Make word segmentation editor editable

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/pecha-tool-for-word-segmentation#8]
## description
Put an option to edit the original text in the Editor so that the annotator can edit the text when needed

## steps

- [x]  add Edit option on the tex

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new 'Edit' tab to allow users to edit the original text. Implemented functionality to switch between 'Segmentor' and 'Edit' modes, and added buttons to confirm edits or undo changes.

You can review changes in this commit: https://github.com/mnmnk43434/OpenPecha-pecha-tool-for-word-segmentation-8/commit/ffa60355cf74a5fd8f0cb828d995adaced7b15a5.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by tenkus47** [comment]
@kaldan007 problem is resolved by adding a edit button on page  where user can click on edit button and edit the text and 
modify the segmentation after that.
